### ISSUE TITLE
Interface Conversion Error

### ISSUE THREAD

**Issue by murdinc** [bep/grouter#4]
Hello! I am just getting started with gopherjs and your gr and grouter packages. So far I like it a lot! I was trying to run the example in /bep/gr/examples/router but I was getting an interface conversion error. 

`router.go:183 Uncaught Error: interface conversion: interface is *js.Object, not map[string]interface {}`

I forked this package to play with it and made some tweaks to get it past this error message. Are you open to pull requests? You can compare my changes here: https://github.com/bep/grouter/compare/master...murdinc:master

**Comment by bep** [comment]
Thanks for the interest -- I had some uncommited changes (sorry about that) -- I took the examples for a spin and they work for me. If you still have problem, a PR is welcomed.

**Comment by murdinc** [comment]
I pulled in the latest commit and it works, so I will go with those changes. Thank you!
